services:
  keion:
    container_name: keion
    image: k_on
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - k_on:latest
    env_file:
      - .env
    init: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "python", "-c", "import discord"]
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
      - type: volume
        source: ffmpeg-cache
        target: /var/cache/ffmpeg
      - type: tmpfs
        target: /var/cache/yt-dlp
        tmpfs:
          size: 50M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - PYTHONOPTIMIZE=2
      - PYTHONASYNCIODEBUG=0
      - FFMPEG_THREADS=2
    sysctls:
      net.core.somaxconn: 1024
    shm_size: 256M
volumes:
  ffmpeg-cache: