name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated version
      - uses: actions/setup-python@v5 # Updated version
        with:
          python-version: "3.12"
          cache: "poetry" # Added caching

      - name: Install Poetry
        run: |
          pipx install poetry # Recommended way to install poetry in CI

      - name: Install dependencies
        run: poetry install --no-interaction # Removed pip install poetry, added --no-interaction

      - name: Run Ruff
        run: poetry run ruff check .
      - name: Run Black
        run: poetry run black --check .
