name: Dependency Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry safety

      - name: Install dependencies
        run: poetry install

      - name: Run safety check
        run: poetry export --format requirements.txt | safety check --stdin